<?php

/**
 * Implements hook_menu().
 */
function dev_menu() {
  $items['admin/config/development/dev'] = array(
    'title' => 'DEV settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dev_settings_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer dev'),
    'file path' => drupal_get_path('module', 'dev'),
    'file' => 'dev.form.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function dev_permission() {
  $items['administer dev'] = array(
    'title' => t('Administer Dev settings'),
  );
  return $items;
}

/**
 * Implements hook_system_info_alter().
 *
 * Changes paths for all modules and themes.
 */
function dev_system_info_alter(&$info, &$file, $type) {
  $dev_drupal_root =& drupal_static(__FUNCTION__);
  // Check this only once per request.
  if (!isset($dev_drupal_root)) {;
    if (variable_get('dev_enabled') && ($git_local_path = variable_get('dev_git_local_path'))) {
      $relative_drupal_root_path = variable_get('dev_relative_drupal_root_path');
      // Multiple slashes are no problem.
      $dev_drupal_root = "$git_local_path/$relative_drupal_root_path";
      // Test arbitrary file.
      if (!file_exists("$dev_drupal_root/includes/bootstrap.inc")) {
        $dev_drupal_root = FALSE;
      }
    }
    else {
      $dev_drupal_root = FALSE;
    }
  }

  $old_file_uri = $file->uri;
  if ($dev_drupal_root) {
    $dev_file_uri = "$dev_drupal_root/$file->uri";
    if (file_exists($dev_file_uri)) {
      $file->uri = $dev_file_uri;
      // This is weird but core wants it.
      $file->filename = $dev_file_uri;
    }
  }
  if (variable_get('dev_debug')) {
    watchdog('dev-debug-sysinfo', '@name: @old, @new',
      array('@name' => $file->name, '@old' => $old_file_uri, '@new' => $file->uri),
      WATCHDOG_DEBUG, 'admin/config/development/dev');
  }
}
